[package]
name = "egui_template"
version = "0.1.0"
authors = ["Emil Ernerfeldt <emilernerfeldt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
egui = "0.5"

# Gives us persistence. Remove if you do like.
serde = { version = "1", features = ["derive"] }

# For compiling natively:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui_glium = "0.5"

# For compiling to web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
egui_web = "0.5"
js-sys = "0.3"
wasm-bindgen = "0.2"

[patch.crates-io]
egui = { git = "https://github.com/emilk/egui", rev = "58c025a7e3d509e93e8f525aa747af1c9bd3dcb1" } # 2020-12-19
egui_glium = { git = "https://github.com/emilk/egui", rev = "58c025a7e3d509e93e8f525aa747af1c9bd3dcb1" } # 2020-12-19
egui_web = { git = "https://github.com/emilk/egui", rev = "58c025a7e3d509e93e8f525aa747af1c9bd3dcb1" } # 2020-12-19

[profile.release]
opt-level = 2 # fast and small wasm
